const CONSTANTS = {
    TOGGLE_LOGIN_MODAL: 'TOGGLE_LOGIN_MODAL',
    TOGGLE_REGISTER_MODAL: 'TOGGLE_REGISTER_MODAL',
    HAVE_ACCOUNT: 'HAVE_ACCOUNT',
    DONT_HAVE_ACCOUNT: 'DONT_HAVE_ACCOUNT'
};

export default  CONSTANTS ;
